### ISSUE TITLE
Working with your own data instructions should reflect `working-with-your-data` location on RStudio Server

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-june-training#11]
My understanding is that the template scripts will need to be copied from `shared-data` per the discussion on [this issue](https://github.com/AlexsLemonade/training-admin/issues/289).

**Comment by cansavvy** [comment]
Should this also be a `training-specific-template` change?

**Comment by jaclyn-taroni** [comment]
Maybe. It depends on if we are going to continue to use that location for these scripts and the SRAdb notebook!

**Comment by jaclyn-taroni** [comment]
Closed via #14.
