### ISSUE TITLE
Final version of the schedule

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-june-training#2]
From the template README:

- [ ] Update `workshop/SCHEDULE.md` to point to appropriate materials for your workshop.
	- Add relative links to PDFs in `slides` to the schedule.
	- We recommend using [htmlpreview](https://github.com/htmlpreview/htmlpreview.github.com) to display rendered versions of R Notebooks that are tied to a specific release in the [`AlexsLemonade/training-modules`](https://github.com/AlexsLemonade/training-modules). You can use the `{{site.release_tag}}` convention used throughout the template.

**Comment by jashapiro** [comment]
I believe this is ready? Any final schedule updates, or do we want to wait for the great tag update to close it?

**Comment by jaclyn-taroni** [comment]
Yes re: waiting for the tag - also want to remove the mention of the draft schedule + note that all times are in Eastern Time.
