### ISSUE TITLE
Slides: Add Introduction to RStudio PDF

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-june-training#21]
Splitting up #4 for tracking purposes

On day 1, we have a set of slides that introduces RStudio and also includes (for 2020 May) some information about reproducibility.

**Comment by jaclyn-taroni** [comment]
@jashapiro I'm going to assign you to this in case you want to make changes compared to the 2020 May version of these slides.

**Comment by jashapiro** [comment]
closed by #30
