### ISSUE TITLE
Slides: Add Introduction to the workshop

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-june-training#22]
Splitting up #4 

The structure of this workshop will be different from 2020 May. This includes some instruction everyday, but it also includes group work to support a larger class size that we should set expectations around (depends on #15).

We should still introduce Kurt, but the communications team folks are not scheduled to join us and Deepa probably won't be testing in the interest of time.

**Comment by jashapiro** [comment]
closed by #30
