### ISSUE TITLE
Update consultation session instructions

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/2020-june-training#28]
The current discussion of consultation sessions in `workshop-structure.md` does not reflect the changes we are planning with regard to Zoom breakout room sessions. In particular, we probably want to add that questions to the small group are encouraged in addition to posts in Slack.

People are likely to want to turn off zoom as well, how will that work as far as rejoining? are they sent back to their breakout room? I don't remember if we tested that specifically.

**Comment by jaclyn-taroni** [comment]
Addressed / superseded by #29
